# Numpy:

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.


In [1]:
import numpy as np

In [2]:
L=[1,2,3,4]
a=np.array(L)
a

array([1, 2, 3, 4])

In [3]:
a.dtype#returns no of dimensions

dtype('int32')

In [5]:
a.ndim#returns no of dimensions 2-(row,cols),1-rows

1

In [6]:
L1=[5,6,7,8]
a2=np.array(L1)
a2

array([5, 6, 7, 8])

## Performing mathematical operations on list, ndarray

In [7]:
L+L1#concatenation

[1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
a+a2#performs additions of respective elements

array([ 6,  8, 10, 12])

In [10]:
L*L1#Error

TypeError: can't multiply sequence by non-int of type 'list'

In [11]:
L1*3#Replication

[5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8]

In [13]:
a2*a#Performs multiplication of resp elements

array([ 5, 12, 21, 32])

In [14]:
a2*3#It multiplies array elements by 3

array([15, 18, 21, 24])

In [15]:
L1*3.5

TypeError: can't multiply sequence by non-int of type 'float'

In [16]:
a2*3.5

array([17.5, 21. , 24.5, 28. ])

In [17]:
a2*'Hi'

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [18]:
L1/2#Error

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [19]:
a2/2

array([2.5, 3. , 3.5, 4. ])

In [20]:
L1**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [21]:
a2**2

array([25, 36, 49, 64], dtype=int32)

In [ ]:
a2/a

## Now we will handle 2-D array

In [27]:
L2=[[2,3,4,5],[6,7,8,9],[11,12,13,14]]
L3=[[11,22,33,44],[21,22,23,24],[31,32,33,34]]

In [28]:
b1=np.array(L2)
b2=np.array(L3)
b1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [29]:
b2

array([[11, 22, 33, 44],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [30]:
L2+L3

[[2, 3, 4, 5],
 [6, 7, 8, 9],
 [11, 12, 13, 14],
 [11, 22, 33, 44],
 [21, 22, 23, 24],
 [31, 32, 33, 34]]

In [31]:
b1+b2

array([[13, 25, 37, 49],
       [27, 29, 31, 33],
       [42, 44, 46, 48]])

In [32]:
b1.ndim

2

In [34]:
b1.shape#Returns shape of array containing (rows,cols)

(3, 4)

In [35]:
b1.dtype

dtype('int32')

In [40]:
b1.max()

14

In [42]:
b1.min()

2

In [43]:
b1.size

12

In [44]:
b1.dot(b2)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [48]:
b1=b1.reshape(4,3)

In [49]:
b1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 11],
       [12, 13, 14]])

In [50]:
b2=b2.reshape(4,3)

In [51]:
b1.dot(b2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [52]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [53]:
v.dot(w)

219

In [54]:
b1.sum()

94

In [55]:
np.sum(b1,axis=0)

array([27, 31, 36])

In [56]:
np.sum(b1,axis=1)

array([ 9, 18, 28, 39])

## Performing slicing/selection on arrays

In [57]:
b1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 11],
       [12, 13, 14]])

In [58]:
b1[3]

array([12, 13, 14])

In [59]:
b1[3][2]

14

In [60]:
b1[:2,:2]#array_name[row index, col index]

array([[2, 3],
       [5, 6]])

In [62]:
b1[:3, 1:]#first 3 rows and last 2 cols

array([[ 3,  4],
       [ 6,  7],
       [ 9, 11]])

In [63]:
b1[:3, -2:]

array([[ 3,  4],
       [ 6,  7],
       [ 9, 11]])

In [64]:
# last 2 rows and last 2 cols
b1[2:, 1:]

array([[ 9, 11],
       [13, 14]])

In [65]:
b1[-2:, -2:]

array([[ 9, 11],
       [13, 14]])

In [66]:
b1[::2, :]

array([[ 2,  3,  4],
       [ 8,  9, 11]])

In [67]:
b1[::2, ::2]

array([[ 2,  4],
       [ 8, 11]])

In [68]:
b1[::-1,:]

array([[12, 13, 14],
       [ 8,  9, 11],
       [ 5,  6,  7],
       [ 2,  3,  4]])

In [71]:
b1[::-1,::-1]

array([[14, 13, 12],
       [11,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [72]:
b1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 11],
       [12, 13, 14]])

In [73]:
b1[[0,2,3],:]

array([[ 2,  3,  4],
       [ 8,  9, 11],
       [12, 13, 14]])

# Creating array with random module

In [78]:
a1=np.random.rand(3,3)#It will create random array of the range[0,1]
a1

array([[0.55108302, 0.78783233, 0.35772086],
       [0.94421425, 0.45311703, 0.25368309],
       [0.37840558, 0.50839037, 0.25520146]])

In [80]:
a2=np.random.randn(3,3)##It will create random array of the range[0,1] with mean values(it includes -ve values)
a2

array([[ 0.34932891, -1.35627092, -1.45362159],
       [ 1.70540726,  0.03322213,  1.00571975],
       [ 0.5484227 , -0.31554747, -0.14780705]])

In [84]:
a3=np.random.random((3,3))#It will create random array of the range[0,1]
a3

array([[0.80633991, 0.89260913, 0.73312647],
       [0.28208446, 0.57213319, 0.0904523 ],
       [0.38916118, 0.6201001 , 0.27585577]])

In [85]:
a4=np.random.randint(40,98,size=(5,5))#It creates random array with start and stop given of given size(both start and stop are included)
a4

array([[84, 90, 76, 88, 91],
       [74, 63, 76, 71, 97],
       [64, 50, 55, 89, 42],
       [54, 51, 92, 56, 92],
       [48, 91, 72, 94, 85]])

In [86]:
a4.size

25

In [87]:
a4.ndim

2

In [100]:
a4

array([[84, 90, 76, 88, 91],
       [74, 63, 76, 71, 97],
       [64, 50, 55, 89, 42],
       [54, 51, 92, 56, 92],
       [48, 91, 72, 94, 85]])

In [99]:
a5=np.random.choice(list('sagar'))#it selects random element from given seq
a5

'g'

In [103]:
np.random.shuffle(a4)
a4

array([[74, 63, 76, 71, 97],
       [48, 91, 72, 94, 85],
       [84, 90, 76, 88, 91],
       [64, 50, 55, 89, 42],
       [54, 51, 92, 56, 92]])

In [105]:
f=np.loadtxt('file_oop.txt',dtype='object')#it reads file in numpy
f

array([['The', 'Square', 'of', '1', 'is', '1'],
       ['The', 'Square', 'of', '2', 'is', '4'],
       ['The', 'Square', 'of', '3', 'is', '9'],
       ['The', 'Square', 'of', '4', 'is', '16'],
       ['The', 'Square', 'of', '5', 'is', '25'],
       ['The', 'Square', 'of', '6', 'is', '36'],
       ['The', 'Square', 'of', '7', 'is', '49'],
       ['The', 'Square', 'of', '8', 'is', '64'],
       ['The', 'Square', 'of', '9', 'is', '81'],
       ['The', 'Square', 'of', '10', 'is', '100'],
       ['The', 'Square', 'of', '11', 'is', '121'],
       ['The', 'Square', 'of', '12', 'is', '144'],
       ['The', 'Square', 'of', '13', 'is', '169'],
       ['The', 'Square', 'of', '14', 'is', '196'],
       ['The', 'Square', 'of', '15', 'is', '225'],
       ['The', 'Square', 'of', '16', 'is', '256'],
       ['The', 'Square', 'of', '17', 'is', '289'],
       ['The', 'Square', 'of', '18', 'is', '324'],
       ['The', 'Square', 'of', '19', 'is', '361'],
       ['The', 'Square', 'of', '20', 'is', '400']], 

In [106]:
f.shape

(20, 6)

In [108]:
np.savetxt('numpy_file_array.txt',f)#it will save file to local directory in numpy

TypeError: Mismatch between array dtype ('object') and format specifier ('%.18e %.18e %.18e %.18e %.18e %.18e')